{{- if .Values.gateway.enabled -}}
{{- range $name, $route := .Values.gateway.route -}}
{{- if $route.enabled -}}
{{- if $.Values.gateway.ingress.enabled -}}
{{- fail "You have selected both gateway.ingress.enabled and a gateway route, you must select either ingress or route but not both" -}}
{{- end -}}
{{- $routeName := ternary (include "loki.gatewayFullname" $) (printf "%s-%s" (include "loki.gatewayFullname" $) $name) (eq $name "main") -}}
{{- include "loki.route" (dict "ctx" $ "route" $route "name" $routeName "port" $.Values.gateway.service.port) }}
{{- end -}}
{{- end -}}
{{- end -}}
