{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.component" (dict "target" "bloom-builder" "component" .Values.bloomBuilder "ctx" .) }}
{{- end }}
