{{- if .Values.vpa.enabled }}

{{- $vpa := .Values.vpa | default dict }}
{{- $target := $vpa.target | default dict }}
{{- $container := $vpa.container | default dict }}

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "grafana.fullname" . }}-vpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: {{ default "apps/v1" $target.apiVersion | quote }}
    kind: {{ default "Deployment" $target.kind | quote }}
    name: {{ default (include "grafana.fullname" .) $target.name | quote }}
  updatePolicy:
    updateMode: {{ default "Off" $vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ default "grafana" $container.name | quote }}
        controlledResources:
          - cpu
          - memory

{{- end }}