{{- if and .Values.queryFrontend.query.enabled .Values.queryFrontend.route.enabled -}}
{{- $dict := dict "ctx" . "component" "query-frontend" -}}
{{- include "tempo.route" (dict "ctx" . "route" .Values.queryFrontend.route "component" "query-frontend" "serviceName" (include "tempo.resourceName" $dict) "servicePort" .Values.queryFrontend.service.port) }}
{{- end }}
