{{- $isSingleBinary := eq (include "loki.deployment.isSingleBinary" .) "true" -}}
{{- if $isSingleBinary -}}
{{- include "loki.pdb" (dict "target" "single-binary" "component" (mergeOverwrite (dict) .Values.singleBinary (.Values.podDisruptionBudget | default dict)) "ctx" . "name" (include "loki.fullname" .)) }}
{{- end }}
