#!/usr/bin/env bash
# Auto-generate .github/advanced-issue-labeler.yml from chart directories.
cat << HEADER
# This file is auto-generated by scripts/generate-labeler.sh. Do not edit manually.

policy:
  - template: [bug_report.yml, feature_request.yml]
    section:
      - id: [chart-name]
        label:
HEADER

for chart in $(ls -1 charts); do
cat << CHARTS
          - name: "chart/${chart}"
            keys: ["${chart}"]
CHARTS
done
