ingest:
  kafka:
    address: "kafka.kafka-ci.svc.cluster.local:9092"
    auto_create_topic_default_partitions: 1

storage:
  trace:
    block:
      version: vParquet4
      dedicated_columns:
        - name: cluster
          type: string
          scope: resource
        - name: service.name
          type: string
          scope: resource
