blockBuilder:
  enabled: false
liveStore:
  enabled: false

ingest:
  kafka:
    address: "kafka.kafka-ci.svc.cluster.local:9092"

storage:
  trace:
    block:
      version: vParquet4
      dedicated_columns:
        - name: cluster
          type: string
          scope: resource
        - name: service.name
          type: string
          scope: resource
